apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asgard

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - mongodb.yaml
  - nysus.yaml
  - giru.yaml
  - percila.yaml

commonLabels:
  app.kubernetes.io/name: asgard
  app.kubernetes.io/version: "2.0.0"
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pandora
