apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asgard

resources:
  - namespace.yaml
  - secrets.yaml
  - nysus/deployment.yaml
  - nysus/service.yaml
  - silenus/deployment.yaml
  - hunoid/deployment.yaml
  - giru/deployment.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml

commonLabels:
  app.kubernetes.io/name: asgard
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
